### PR TITLE
CD-126492 Azure - Slowness while uploading/accessing records with attachments (By commenting out the retry filter)

### PR DESCRIPTION
**Pull request by revathi-murali**
## Jira Ticket
[Main Jira ticket ](https://coupadev.atlassian.net/browse/CD-126492)

## Code Reviewers
- [ ] @tjackiw 

## Summary of issue

- In most of the places, paperclip [checks if the attachment exists](https://github.com/thoughtbot/paperclip/blob/v5.3.0/lib/paperclip/attachment.rb#L569) in cloud before doing some of the operations. Azure interface throws 404 when blob does not exist. This is being retried exponentially as we have enabled retry policy. Once the retry is done, [this error with 404 status code is rescued](https://github.com/coupa/paperclip-azure/blob/master/lib/paperclip/storage/azure.rb#L185) and then returned `false` when we call exists? method on attachment. 

- The slowness in the app is because of the retry being done exponentially

## Summary of change

Commenting out the `ExponentialRetryPolicyFilter` for azure blob service

 **_Can we use LinearRetryFiler instead of ExponentialRetryPolicyFilter_?**
  **_Ans_:** No.We see issues with LinearRetryPolicy for which the issue is raised in [azure-storage-ruby repo](https://github.com/Azure/azure-storage-ruby/issues/121) and hence we enabled exponential retry filter with smaller retry values. But see slowness even with that :(

### CODE REVIEW

**Comment by saghaulor** [comment]
Does Azure not support an `exists?` type function? It seems inappropriate to remove exponential retry from the entire gem.

**Comment by saghaulor** [comment]
Please add myself or @johnny-lai as a reviewer. We should use two reviewer process for our dependencies as well.

**Comment by johnny-lai** [comment]
So usually we want retries...

From https://github.com/Azure/azure-storage-ruby/blob/master/common/lib/azure/storage/common/core/filter/retry_filter.rb#L55, it looks like there's a way to turn off the retries?

Or.. we could have 2 `obtain_azure_instance_for`. One that has retries, and one without. And we use the non-retry version for `exists?` only?

**Comment by johnny-lai** [comment]
Separately, perhaps we could also reduce the retry count? What is the current retry count and delays?

**Comment by revathi-murali** [comment]
@johnny-lai 

1. `retry_data[:retryable].nil?` is set to nil for the first time when the retry filter is enabled. Hence `retry_data[:retryable] = true` is always set. I don't think we can turn off retries here.

2. Reducing the count further did not help as the retry logic is made exponential. Currently seeing a delay of atleast 30s to 40s for one attachment

3. I have modified the code to use the non retry version for `exists?` method in this PR #5. Can you please check if it looks good.

**Comment by aldokurnia-coupa** [comment]
@revathi-murali @tjackiw could you merge this PR and tag it if it's ready?

**Comment by tjackiw** [comment]
Closing in favor of #5

**Pull request closed without merging**
